### ISSUE TITLE
Se rendeu para a Ciência de Dados com Python 

### ISSUE THREAD

**Issue by marcosdsdba** [andremrezende/python-datascience#1]
# Se rendeu ao Python então

#### Recomento os Cursos:
*Tem vários gratuitos*

[DIO](https://digitalinnovation.one/)

[IGIT-BOOTCAMPS](https://www.igti.com.br/bootcamp/cientista-de-dados)

[EIA](https://www.eia.ai/)

[DSA](https://www.datascienceacademy.com.br/)

###### E vou te mandar no seu e-mail mais cursos dentro de um Google Drive.

>Forte Abraço 
>Bem-vindo a Ciência de Dados com Python.

**Comment by marcosdsdba** [comment]
https://digitalinnovation.one/bootcamps/banco-carrefour-data-engineer

**Comment by andremrezende** [comment]
@marcosdsdba https://www.youtube.com/watch?v=jvYQXvMBx9k

> https://digitalinnovation.one/bootcamps/banco-carrefour-data-engineer

**Comment by marcosdsdba** [comment]
https://www.udemy.com/course/bootcamp-de-data-science-com-python/  
CUPOM: FREEDATA

**Comment by marcosdsdba** [comment]
BELA CIAO
